-- Espécies mais usadas em bonsai (clássicas japonesas/chinesas, europeias, tropicais e nativas do Brasil).
-- Rodar no SQL Editor do Neon. Idempotente: espécies com o mesmo nomeCientifico já cadastradas são ignoradas.
-- O id é gerado aqui (o @default(uuid()) do Prisma não existe no banco).

INSERT INTO "Especie" (
  "id", "nomeCientifico", "nomeComum", "familia", "origem", "tipoDePlanta", "status",
  "luminosidade", "rega", "clima", "observacoes"
)
SELECT
  gen_random_uuid()::text, v.nc, v.nome, v.familia, v.origem, v.tipo::"TipoPlanta", 'VERIFICADO'::"StatusEspecie",
  v.luz, v.rega, v.clima, v.obs
FROM (VALUES
  -- ===================== CONÍFERAS =====================
  ('Juniperus chinensis', 'Junípero-chinês', 'Cupressaceae', 'China, Japão', 'CONIFERA',
   'Sol pleno.', 'Moderada; regar quando a superfície do substrato começar a secar. Gosta de borrifar a folhagem.', 'Temperado a subtropical; precisa de período de repouso no inverno.',
   'Clássico para jin e shari. Pinçar os brotos com os dedos; evitar tesoura na folhagem.'),
  ('Juniperus procumbens ''Nana''', 'Junípero-procumbens (junípero-anão)', 'Cupressaceae', 'Japão', 'CONIFERA',
   'Sol pleno.', 'Moderada; não deixar encharcar.', 'Temperado a subtropical; muito bem adaptado ao Brasil.',
   'Um dos mais vendidos no Brasil. Ótimo para iniciantes e para estilos cascata e semicascata.'),
  ('Juniperus sabina', 'Sabina', 'Cupressaceae', 'Europa, Ásia Central', 'CONIFERA',
   'Sol pleno.', 'Moderada; tolera bem a seca.', 'Temperado, resistente ao frio.',
   'Madeira morta muito bonita. Folhagem escamiforme.'),
  ('Juniperus rigida', 'Junípero-agulha', 'Cupressaceae', 'Japão, Coreia, China', 'CONIFERA',
   'Sol pleno.', 'Moderada.', 'Temperado; precisa de inverno frio.',
   'Folhagem em agulha, muito usado em bonsais de exposição.'),
  ('Juniperus communis', 'Zimbro-comum', 'Cupressaceae', 'Hemisfério Norte', 'CONIFERA',
   'Sol pleno.', 'Moderada.', 'Temperado a frio.',
   'Folhagem em agulha; ótimo para yamadori na Europa.'),
  ('Pinus thunbergii', 'Pinheiro-negro-japonês', 'Pinaceae', 'Japão, Coreia', 'CONIFERA',
   'Sol pleno.', 'Moderada; deixar secar levemente entre regas.', 'Temperado a subtropical; tolera calor e vento.',
   'Técnica de corte de velas no verão para reduzir agulhas e gerar segunda brotação.'),
  ('Pinus parviflora', 'Pinheiro-branco-japonês', 'Pinaceae', 'Japão', 'CONIFERA',
   'Sol pleno a meia-sombra no verão.', 'Moderada; sensível ao encharcamento.', 'Temperado; não gosta de calor intenso.',
   'Agulhas curtas em grupos de cinco. Normalmente enxertado.'),
  ('Pinus densiflora', 'Pinheiro-vermelho-japonês', 'Pinaceae', 'Japão, Coreia, China', 'CONIFERA',
   'Sol pleno.', 'Moderada.', 'Temperado.',
   'Casca avermelhada; muito usado no estilo bunjin (literati).'),
  ('Pinus sylvestris', 'Pinheiro-silvestre', 'Pinaceae', 'Europa, Ásia', 'CONIFERA',
   'Sol pleno.', 'Moderada.', 'Temperado a frio.',
   'Casca alaranjada no topo. Uma brotação por ano: pinçar as velas na primavera.'),
  ('Pinus mugo', 'Pinheiro-montanhês', 'Pinaceae', 'Montanhas da Europa', 'CONIFERA',
   'Sol pleno.', 'Moderada.', 'Temperado a frio.',
   'Muito usado como yamadori; tronco retorcido natural.'),
  ('Pinus elliottii', 'Pinus-elliottii', 'Pinaceae', 'Sudeste dos EUA', 'CONIFERA',
   'Sol pleno.', 'Moderada.', 'Subtropical; muito comum no Sul e Sudeste do Brasil.',
   'Fácil de achar no Brasil. Agulhas longas, exige técnicas de redução.'),
  ('Larix kaempferi', 'Lariço-japonês', 'Pinaceae', 'Japão', 'CONIFERA',
   'Sol pleno.', 'Generosa no verão.', 'Temperado; precisa de inverno frio.',
   'Conífera caducifólia: perde as agulhas no outono.'),
  ('Larix decidua', 'Lariço-europeu', 'Pinaceae', 'Europa', 'CONIFERA',
   'Sol pleno.', 'Generosa no verão.', 'Temperado a frio.',
   'Conífera caducifólia, ótima para grupos (floresta).'),
  ('Taxus cuspidata', 'Teixo-japonês', 'Taxaceae', 'Japão, Coreia, China', 'CONIFERA',
   'Meia-sombra a sol.', 'Moderada; manter levemente úmido.', 'Temperado.',
   'Aceita poda em madeira velha. Sementes e folhas tóxicas.'),
  ('Chamaecyparis obtusa', 'Hinoki', 'Cupressaceae', 'Japão', 'CONIFERA',
   'Sol a meia-sombra.', 'Regular; não deixar secar totalmente.', 'Temperado.',
   'Pinçar a folhagem com os dedos; o interior seca se ficar sem luz.'),
  ('Chamaecyparis pisifera', 'Sawara', 'Cupressaceae', 'Japão', 'CONIFERA',
   'Sol a meia-sombra.', 'Regular.', 'Temperado.',
   'Várias cultivares de folhagem fina; boa para iniciantes.'),
  ('Cryptomeria japonica', 'Criptoméria (cedro-japonês)', 'Cupressaceae', 'Japão, China', 'CONIFERA',
   'Sol pleno a meia-sombra.', 'Regular; gosta de umidade.', 'Temperado a subtropical.',
   'Ideal para estilo formal ereto e florestas.'),
  ('Taxodium distichum', 'Cipreste-calvo', 'Cupressaceae', 'Sudeste dos EUA', 'CONIFERA',
   'Sol pleno.', 'Abundante; tolera ficar com o vaso em pratinho com água.', 'Temperado a subtropical.',
   'Conífera caducifólia; tronco largo na base (estilo flat-top).'),
  ('Metasequoia glyptostroboides', 'Metassequoia', 'Cupressaceae', 'China', 'CONIFERA',
   'Sol pleno.', 'Abundante.', 'Temperado.',
   'Conífera caducifólia de crescimento rápido; ótima para florestas.'),
  ('Podocarpus macrophyllus', 'Podocarpo', 'Podocarpaceae', 'Japão, China', 'CONIFERA',
   'Sol a meia-sombra.', 'Regular.', 'Subtropical; muito bem adaptado ao Brasil.',
   'Comum em jardins brasileiros; tolera ambientes com menos luz.'),
  ('Sequoia sempervirens', 'Sequoia-vermelha', 'Cupressaceae', 'Costa da Califórnia (EUA)', 'CONIFERA',
   'Sol a meia-sombra.', 'Regular; gosta de umidade.', 'Temperado.',
   'Crescimento vigoroso; bom para estilo formal e floresta.'),
  ('Cedrus atlantica', 'Cedro-do-atlas', 'Pinaceae', 'Norte da África', 'CONIFERA',
   'Sol pleno.', 'Moderada.', 'Temperado.',
   'Cultivar ''Glauca'' tem folhagem azulada.'),
  ('Cedrus deodara', 'Cedro-do-himalaia', 'Pinaceae', 'Himalaia', 'CONIFERA',
   'Sol pleno.', 'Moderada.', 'Temperado a subtropical.',
   'Ramos pendentes; agulhas longas para bonsai.'),
  ('Picea abies', 'Abeto-vermelho (espruce-europeu)', 'Pinaceae', 'Europa', 'CONIFERA',
   'Sol a meia-sombra.', 'Regular.', 'Temperado a frio.',
   'Cultivares anãs são muito usadas. Não tolera calor intenso.'),
  ('Cupressus macrocarpa', 'Cipreste-de-monterey (tuia-limão)', 'Cupressaceae', 'Califórnia (EUA)', 'CONIFERA',
   'Sol pleno.', 'Moderada.', 'Temperado a subtropical.',
   'Cultivar ''Goldcrest'' (tuia-limão) é muito vendida no Brasil.'),
  ('Platycladus orientalis', 'Tuia-oriental', 'Cupressaceae', 'China, Coreia', 'CONIFERA',
   'Sol pleno.', 'Moderada.', 'Temperado a subtropical.',
   'Folhagem em leque; fácil de achar no Brasil.'),

  -- ===================== CADUCIFÓLIAS =====================
  ('Acer palmatum', 'Bordo-japonês (ácer)', 'Sapindaceae', 'Japão, Coreia, China', 'CADUCIFOLIA',
   'Sol da manhã e sombra à tarde no verão.', 'Regular; não deixar secar.', 'Temperado; prefere regiões de altitude no Brasil.',
   'Cores intensas no outono. Folhas queimam com sol forte e vento.'),
  ('Acer buergerianum', 'Bordo-tridente', 'Sapindaceae', 'China, Japão', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Temperado a subtropical; tolera calor.',
   'Ótimo nebari e cicatrização rápida. Muito usado para estilo raiz sobre pedra.'),
  ('Acer campestre', 'Bordo-campestre', 'Sapindaceae', 'Europa', 'CADUCIFOLIA',
   'Sol a meia-sombra.', 'Regular.', 'Temperado.',
   'Ramificação fina e folhas pequenas.'),
  ('Ulmus parvifolia', 'Olmo-chinês', 'Ulmaceae', 'China, Japão, Coreia', 'SEMI_CADUCA',
   'Sol pleno a meia-sombra.', 'Regular.', 'Temperado a tropical; muito adaptável.',
   'Excelente para iniciantes. Vende-se muito como bonsai de entrada.'),
  ('Zelkova serrata', 'Zelkova', 'Ulmaceae', 'Japão, Coreia, China', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular; gosta de umidade.', 'Temperado.',
   'Ideal para o estilo vassoura (hokidachi).'),
  ('Carpinus betulus', 'Carpino-europeu', 'Betulaceae', 'Europa', 'CADUCIFOLIA',
   'Sol a meia-sombra.', 'Regular.', 'Temperado.',
   'Tronco cinza liso; folhas secas ficam presas no inverno.'),
  ('Carpinus turczaninowii', 'Carpino-coreano', 'Betulaceae', 'Coreia, China, Japão', 'CADUCIFOLIA',
   'Sol a meia-sombra.', 'Regular.', 'Temperado.',
   'Folhas pequenas e boa ramificação; muito valorizado.'),
  ('Fagus crenata', 'Faia-japonesa', 'Fagaceae', 'Japão', 'CADUCIFOLIA',
   'Meia-sombra no verão.', 'Regular.', 'Temperado; precisa de inverno frio.',
   'Casca clara; usada em florestas. Uma brotação por ano.'),
  ('Fagus sylvatica', 'Faia-europeia', 'Fagaceae', 'Europa', 'CADUCIFOLIA',
   'Sol a meia-sombra.', 'Regular.', 'Temperado.',
   'Mantém folhas secas no inverno (marcescência).'),
  ('Quercus robur', 'Carvalho-europeu', 'Fagaceae', 'Europa', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Temperado.',
   'Tronco robusto; folhas reduzem lentamente.'),
  ('Ginkgo biloba', 'Ginkgo', 'Ginkgoaceae', 'China', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Temperado a subtropical.',
   'Fóssil vivo. Amarelo intenso no outono; não aceita bem aramação.'),
  ('Liquidambar styraciflua', 'Liquidâmbar', 'Altingiaceae', 'América do Norte', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Temperado a subtropical; comum no Sul do Brasil.',
   'Folhagem colorida no outono.'),
  ('Celtis sinensis', 'Lódão-chinês', 'Cannabaceae', 'China, Japão, Coreia', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Temperado a subtropical.',
   'Ramificação fina, semelhante à zelkova.'),
  ('Morus alba', 'Amoreira', 'Moraceae', 'China', 'CADUCIFOLIA',
   'Sol pleno.', 'Abundante no verão.', 'Temperado a tropical; cresce muito bem no Brasil.',
   'Crescimento rápido e frutificação. Poda frequente para reduzir folhas.'),
  ('Malus halliana', 'Macieira-de-flor', 'Rosaceae', 'China', 'CADUCIFOLIA',
   'Sol pleno.', 'Abundante na floração e frutificação.', 'Temperado.',
   'Flores rosadas e frutos pequenos. Precisa de frio para florir.'),
  ('Prunus mume', 'Damasqueiro-japonês (ume)', 'Rosaceae', 'China', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Temperado.',
   'Floresce no fim do inverno. Podar logo após a floração.'),
  ('Prunus serrulata', 'Cerejeira-japonesa', 'Rosaceae', 'Japão, China, Coreia', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Temperado; precisa de frio para florir.',
   'Cicatriza mal: evitar grandes cortes.'),
  ('Chaenomeles speciosa', 'Marmeleiro-do-japão', 'Rosaceae', 'China', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Temperado a subtropical.',
   'Floração vermelha, rosa ou branca no fim do inverno. Emite muitos rebentos da base.'),
  ('Pseudocydonia sinensis', 'Marmeleiro-chinês', 'Rosaceae', 'China', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Temperado.',
   'Casca que descama em placas coloridas.'),
  ('Crataegus monogyna', 'Pilriteiro', 'Rosaceae', 'Europa', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Temperado.',
   'Flores brancas e frutos vermelhos; muito usado como yamadori.'),
  ('Punica granatum', 'Romãzeira', 'Lythraceae', 'Irã, Ásia Central', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular; reduzir no inverno.', 'Subtropical a tropical; muito bem adaptada ao Brasil.',
   'Flores laranja e frutos; cultivar ''Nana'' é anã. Tronco torce com a idade.'),
  ('Wisteria floribunda', 'Glicínia', 'Fabaceae', 'Japão', 'CADUCIFOLIA',
   'Sol pleno.', 'Abundante; pode ficar com pratinho com água no verão.', 'Temperado a subtropical.',
   'Cachos de flores pendentes. Podar logo após a floração.'),
  ('Lagerstroemia indica', 'Resedá (extremosa)', 'Lythraceae', 'China, Sudeste Asiático', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Subtropical a tropical; muito comum no Brasil.',
   'Casca lisa que descama; flores no verão.'),
  ('Diospyros rhombifolia', 'Caqui-anão', 'Ebenaceae', 'China', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Temperado a subtropical.',
   'Frutinhos laranja que ficam após a queda das folhas.'),
  ('Tamarix chinensis', 'Tamargueira', 'Tamaricaceae', 'China', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Temperado a subtropical; tolera maresia.',
   'Folhagem plumosa; crescimento rápido.'),
  ('Handroanthus impetiginosus', 'Ipê-roxo', 'Bignoniaceae', 'Brasil', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular; reduzir no inverno quando perde as folhas.', 'Tropical a subtropical.',
   'Nativa. Floração no fim do inverno, sem folhas; floresce com idade.'),
  ('Handroanthus chrysotrichus', 'Ipê-amarelo', 'Bignoniaceae', 'Brasil', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular; reduzir no inverno.', 'Tropical a subtropical.',
   'Nativa. Engrossa o tronco rápido em solo; folhas compostas grandes.'),
  ('Paubrasilia echinata', 'Pau-brasil', 'Fabaceae', 'Mata Atlântica (Brasil)', 'SEMI_CADUCA',
   'Sol pleno.', 'Regular.', 'Tropical; sensível ao frio.',
   'Nativa ameaçada (adquirir só de viveiros legalizados). Tronco com espinhos.'),
  ('Libidibia ferrea', 'Pau-ferro', 'Fabaceae', 'Brasil', 'SEMI_CADUCA',
   'Sol pleno.', 'Regular.', 'Tropical a subtropical.',
   'Nativa. Casca manchada que descama; folhas miúdas.'),

  -- ===================== PERENES / TROPICAIS =====================
  ('Ficus microcarpa', 'Ficus (figueira-chinesa, ficus-ginseng)', 'Moraceae', 'Sudeste Asiático, Oceania', 'PERENE',
   'Sol pleno a meia-sombra; tolera interior com boa luz.', 'Regular; deixar secar a superfície.', 'Tropical a subtropical; proteger abaixo de 10 °C.',
   'O bonsai mais vendido do mundo. Emite raízes aéreas; aceita desfolha total.'),
  ('Ficus benjamina', 'Figueira-benjamim', 'Moraceae', 'Sul e Sudeste Asiático', 'PERENE',
   'Muita luz; sol da manhã.', 'Regular.', 'Tropical; não gosta de mudanças de lugar.',
   'Pode derrubar folhas ao mudar de ambiente. Seiva irritante.'),
  ('Ficus neriifolia', 'Ficus-salgueiro (Ficus salicaria)', 'Moraceae', 'Himalaia, Sul da China', 'PERENE',
   'Sol a meia-sombra.', 'Regular.', 'Tropical a subtropical.',
   'Folhas finas e pequenas; ótima ramificação.'),
  ('Ficus religiosa', 'Figueira-sagrada', 'Moraceae', 'Índia', 'SEMI_CADUCA',
   'Sol pleno.', 'Regular.', 'Tropical.',
   'Folhas em forma de coração com ponta longa.'),
  ('Carmona retusa', 'Chá-de-Fukien (Carmona)', 'Boraginaceae', 'Sul da China, Sudeste Asiático', 'PERENE',
   'Muita luz, sem sol forte da tarde.', 'Regular; não deixar secar.', 'Tropical; sensível ao frio.',
   'Flores brancas e frutinhos vermelhos o ano todo.'),
  ('Serissa japonica', 'Serissa (árvore-das-mil-estrelas)', 'Rubiaceae', 'Sudeste Asiático', 'PERENE',
   'Muita luz, sol da manhã.', 'Regular; sensível a extremos.', 'Subtropical; não tolera geada.',
   'Flores brancas pequenas. Raízes com odor característico ao podar.'),
  ('Sageretia theezans', 'Sagerécia', 'Rhamnaceae', 'Sul da China', 'PERENE',
   'Sol a meia-sombra.', 'Regular; não deixar secar.', 'Subtropical a tropical.',
   'Casca que descama como a do plátano. Folhas pequenas.'),
  ('Portulacaria afra', 'Portulacária (árvore-da-fartura)', 'Didiereaceae', 'África do Sul', 'PERENE',
   'Sol pleno.', 'Pouca; suculenta, regar só com o substrato seco.', 'Subtropical a tropical; não tolera geada.',
   'Muito fácil para iniciantes. Galhos se aramam com cuidado (são quebradiços).'),
  ('Crassula ovata', 'Árvore-de-jade', 'Crassulaceae', 'África do Sul', 'PERENE',
   'Sol pleno a meia-sombra.', 'Pouca; suculenta.', 'Subtropical a tropical.',
   'Estaquia muito fácil. Não aceita bem aramação.'),
  ('Schefflera arboricola', 'Cheflera', 'Araliaceae', 'Taiwan', 'PERENE',
   'Meia-sombra; tolera interior.', 'Regular.', 'Tropical a subtropical.',
   'Boa para interior; emite raízes aéreas.'),
  ('Bougainvillea glabra', 'Primavera (buganvília)', 'Nyctaginaceae', 'Brasil', 'SEMI_CADUCA',
   'Sol pleno (essencial para florir).', 'Moderada; floresce mais com leve estresse hídrico.', 'Tropical a subtropical.',
   'Nativa. Brácteas coloridas; raízes sensíveis no transplante. Tem espinhos.'),
  ('Rhododendron indicum', 'Azaleia-satsuki', 'Ericaceae', 'Japão', 'PERENE',
   'Sol da manhã, sombra à tarde.', 'Regular; usar água pouco calcária.', 'Temperado a subtropical.',
   'Substrato ácido (kanuma). Podar logo após a floração.'),
  ('Buxus sempervirens', 'Buxinho', 'Buxaceae', 'Europa, Norte da África', 'PERENE',
   'Sol a meia-sombra.', 'Regular.', 'Temperado a subtropical.',
   'Madeira densa e folhas pequenas; crescimento lento.'),
  ('Buxus microphylla', 'Buxinho-japonês', 'Buxaceae', 'Japão', 'PERENE',
   'Sol a meia-sombra.', 'Regular.', 'Temperado a subtropical.',
   'Folhas menores que o buxo europeu; tolera bem o calor.'),
  ('Olea europaea', 'Oliveira', 'Oleaceae', 'Mediterrâneo', 'PERENE',
   'Sol pleno.', 'Moderada; tolera seca.', 'Mediterrâneo; vai bem no Sul e em regiões de altitude.',
   'Madeira morta e tronco envelhecido. Aceita poda forte.'),
  ('Ligustrum sinense', 'Ligustro-chinês', 'Oleaceae', 'China', 'SEMI_CADUCA',
   'Sol pleno.', 'Regular.', 'Temperado a tropical.',
   'Muito vigoroso e resistente; ótimo para iniciantes.'),
  ('Murraya paniculata', 'Murta-de-cheiro', 'Rutaceae', 'Sul e Sudeste Asiático', 'PERENE',
   'Sol pleno a meia-sombra.', 'Regular.', 'Tropical a subtropical.',
   'Flores brancas perfumadas; muito comum no Brasil.'),
  ('Myrtus communis', 'Murta-comum', 'Myrtaceae', 'Mediterrâneo', 'PERENE',
   'Sol pleno.', 'Regular.', 'Mediterrâneo a subtropical.',
   'Folhas aromáticas e flores brancas.'),
  ('Pistacia lentiscus', 'Lentisco (aroeira-mediterrânea)', 'Anacardiaceae', 'Mediterrâneo', 'PERENE',
   'Sol pleno.', 'Moderada; tolera seca.', 'Mediterrâneo.',
   'Muito resistente; casca envelhece bem.'),
  ('Pyracantha coccinea', 'Piracanta', 'Rosaceae', 'Sul da Europa, Ásia Menor', 'PERENE',
   'Sol pleno.', 'Regular.', 'Temperado a subtropical.',
   'Frutos vermelhos ou laranja. Espinhos.'),
  ('Cotoneaster horizontalis', 'Cotoneaster', 'Rosaceae', 'China', 'SEMI_CADUCA',
   'Sol pleno.', 'Regular.', 'Temperado.',
   'Folhas miúdas e frutinhos vermelhos; ótimo para shohin.'),
  ('Lonicera nitida', 'Madressilva-arbustiva', 'Caprifoliaceae', 'China', 'PERENE',
   'Sol a meia-sombra.', 'Regular.', 'Temperado.',
   'Folhas minúsculas, crescimento rápido; bom para mame/shohin.'),
  ('Ilex crenata', 'Azevinho-japonês', 'Aquifoliaceae', 'Japão, Coreia', 'PERENE',
   'Sol a meia-sombra.', 'Regular; gosta de umidade.', 'Temperado.',
   'Folhas pequenas, parecido com o buxo.'),
  ('Gardenia jasminoides', 'Gardênia', 'Rubiaceae', 'China', 'PERENE',
   'Muita luz, sem sol forte da tarde.', 'Regular; água pouco calcária.', 'Subtropical.',
   'Flores perfumadas. Prefere substrato ácido.'),
  ('Camellia japonica', 'Camélia', 'Theaceae', 'Japão, China, Coreia', 'PERENE',
   'Meia-sombra.', 'Regular.', 'Temperado a subtropical.',
   'Floresce no inverno. Substrato ácido.'),
  ('Citrus japonica', 'Kumquat (laranjinha-kinkan)', 'Rutaceae', 'China', 'PERENE',
   'Sol pleno.', 'Regular.', 'Subtropical.',
   'Frutificação decorativa e comestível.'),
  ('Adenium obesum', 'Rosa-do-deserto', 'Apocynaceae', 'África, Península Arábica', 'SEMI_CADUCA',
   'Sol pleno.', 'Pouca; suculenta, reduzir muito no inverno.', 'Tropical; não tolera frio.',
   'Caudex engrossado e flores vistosas. Seiva tóxica.'),
  ('Tamarindus indica', 'Tamarindeiro', 'Fabaceae', 'África tropical', 'PERENE',
   'Sol pleno.', 'Regular.', 'Tropical.',
   'Folhas compostas que reduzem bem; tolera desfolha.'),
  ('Terminalia molinetii', 'Bucida (Bucida molinetii)', 'Combretaceae', 'Caribe', 'PERENE',
   'Sol pleno.', 'Regular.', 'Tropical.',
   'Folhas minúsculas e ramificação em camadas; espinhos finos.'),
  ('Casuarina equisetifolia', 'Casuarina', 'Casuarinaceae', 'Sudeste Asiático, Austrália', 'PERENE',
   'Sol pleno.', 'Regular; tolera solo arenoso.', 'Tropical; tolera maresia.',
   'Aparência de conífera; ótima para litoral.'),
  ('Duranta erecta', 'Pingo-de-ouro (duranta)', 'Verbenaceae', 'Américas tropicais', 'PERENE',
   'Sol pleno.', 'Regular.', 'Tropical a subtropical.',
   'Muito comum em cercas vivas no Brasil; fácil de coletar.'),
  ('Calliandra brevipes', 'Esponjinha (caliandra)', 'Fabaceae', 'Sul do Brasil', 'PERENE',
   'Sol pleno.', 'Regular.', 'Subtropical.',
   'Nativa. Flores em pompom rosa e branco.'),
  ('Pleroma granulosum', 'Quaresmeira', 'Melastomataceae', 'Mata Atlântica (Brasil)', 'PERENE',
   'Sol pleno.', 'Regular.', 'Tropical a subtropical.',
   'Nativa (antes Tibouchina granulosa). Flores roxas; folhas grandes.'),

  -- ===================== FRUTÍFERAS (muito usadas no Brasil) =====================
  ('Plinia cauliflora', 'Jabuticabeira', 'Myrtaceae', 'Mata Atlântica (Brasil)', 'PERENE',
   'Sol pleno a meia-sombra.', 'Abundante; não deixar secar.', 'Tropical a subtropical.',
   'Nativa. Frutos no tronco; crescimento lento. Prefere substrato levemente ácido.'),
  ('Myrciaria tenella', 'Cambuí', 'Myrtaceae', 'Brasil', 'PERENE',
   'Sol pleno.', 'Regular.', 'Tropical a subtropical.',
   'Nativa. Folhas minúsculas; uma das melhores nativas para bonsai.'),
  ('Eugenia uniflora', 'Pitangueira', 'Myrtaceae', 'Mata Atlântica (Brasil)', 'SEMI_CADUCA',
   'Sol pleno.', 'Regular.', 'Tropical a subtropical.',
   'Nativa. Casca que descama e frutos vermelhos. Muito resistente.'),
  ('Eugenia brasiliensis', 'Grumixameira', 'Myrtaceae', 'Mata Atlântica (Brasil)', 'PERENE',
   'Sol a meia-sombra.', 'Regular; gosta de umidade.', 'Tropical a subtropical.',
   'Nativa. Frutos roxos; folhas brilhantes.'),
  ('Psidium guajava', 'Goiabeira', 'Myrtaceae', 'América tropical', 'PERENE',
   'Sol pleno.', 'Regular.', 'Tropical a subtropical.',
   'Casca lisa que descama; tolera poda forte.'),
  ('Psidium cattleianum', 'Araçazeiro', 'Myrtaceae', 'Mata Atlântica (Brasil)', 'PERENE',
   'Sol pleno.', 'Regular.', 'Tropical a subtropical; tolera frio.',
   'Nativa. Tronco liso avermelhado e frutos pequenos.'),
  ('Malpighia emarginata', 'Aceroleira', 'Malpighiaceae', 'América Central, Caribe', 'PERENE',
   'Sol pleno.', 'Regular.', 'Tropical.',
   'Folhas pequenas, flores rosadas e frutos; cultivar ''Nana'' é muito usada.'),

  -- ===================== PITHECELLOBIUM / FICUS NATIVOS =====================
  -- Mantido o nome Pithecellobium (como é conhecido no bonsai); nome aceito atual vai na observação.
  ('Pithecellobium tortum', 'Tataré (jacaré)', 'Fabaceae', 'Brasil', 'SEMI_CADUCA',
   'Sol pleno.', 'Regular; tolera curtos períodos de seca.', 'Tropical a subtropical.',
   'Nativa (nome aceito: Chloroleucon tortum). Tronco naturalmente tortuoso, folhas miúdas e casca que engrossa rápido. Muito apreciada no bonsai brasileiro.'),
  ('Pithecellobium dumosum', 'Piteco (jurema-branca)', 'Fabaceae', 'Nordeste do Brasil (Caatinga)', 'SEMI_CADUCA',
   'Sol pleno.', 'Moderada; resistente à seca.', 'Tropical semiárido; sensível a geada.',
   'Nativa (nome aceito: Chloroleucon dumosum). Folíolos minúsculos e ramificação densa; ótima para florestas e shohin.'),
  ('Pithecellobium dulce', 'Mata-fome (guamúchil)', 'Fabaceae', 'México, América Central', 'PERENE',
   'Sol pleno.', 'Regular.', 'Tropical.',
   'Crescimento vigoroso, espinhos nos ramos. Muito usada em bonsai na Índia e no Sudeste Asiático.'),
  ('Ficus clusiifolia', 'Figueira-mata-pau (figueira-vermelha)', 'Moraceae', 'Brasil', 'PERENE',
   'Sol pleno a meia-sombra.', 'Regular.', 'Tropical a subtropical.',
   'Nativa hemiepífita (estranguladora). Raízes aéreas e tronco engrossam rápido.'),
  ('Ficus insipida', 'Figueira-mata-pau (figueira-do-brejo)', 'Moraceae', 'América tropical, Amazônia', 'PERENE',
   'Sol pleno.', 'Abundante; gosta de umidade.', 'Tropical.',
   'Nativa. Folhas grandes que reduzem com desfolha; muito vigorosa.'),
  ('Ficus organensis', 'Figueira-nativa (figueira-de-folha-miúda)', 'Moraceae', 'Sul e Sudeste do Brasil', 'PERENE',
   'Sol pleno.', 'Regular.', 'Subtropical; tolera frio moderado.',
   'Nativa. Folhas pequenas e boa ramificação; uma das melhores figueiras nativas para bonsai.'),

  -- ===================== SUDESTE ASIÁTICO (Vietnã, Indonésia) =====================
  ('Wrightia religiosa', 'Jasmim-d''água (mai chiếu thủy)', 'Apocynaceae', 'Sudeste Asiático', 'PERENE',
   'Sol pleno.', 'Regular; não deixar secar.', 'Tropical; proteger abaixo de 10 °C.',
   'Uma das espécies mais populares do Vietnã. Flores brancas perfumadas pendentes; folhas reduzem bem.'),
  ('Premna serratifolia', 'Premna', 'Lamiaceae', 'Sudeste Asiático, Oceania', 'PERENE',
   'Sol pleno.', 'Regular.', 'Tropical.',
   'Madeira morta muito durável e casca clara; folhas aromáticas. Muito usada no Vietnã e na Indonésia.'),
  ('Premna microphylla', 'Premna-de-folha-miúda (sancang)', 'Lamiaceae', 'China, Sudeste Asiático', 'SEMI_CADUCA',
   'Sol pleno.', 'Regular.', 'Subtropical a tropical.',
   'Folhas pequenas e casca lisa e clara.'),
  ('Hibiscus tiliaceus', 'Waru (algodoeiro-da-praia)', 'Malvaceae', 'Litorais tropicais da Ásia e do Pacífico', 'PERENE',
   'Sol pleno.', 'Regular; tolera maresia.', 'Tropical.',
   'Nome aceito: Talipariti tiliaceum. Clássico do bonsai indonésio; folhas reduzem muito com poda e desfolha. Variedade de folha miúda é a mais valorizada.'),
  ('Pemphis acidula', 'Santigi', 'Lythraceae', 'Litorais do Indo-Pacífico', 'PERENE',
   'Sol pleno.', 'Regular; tolera maresia.', 'Tropical; não tolera frio.',
   'Folhas minúsculas e madeira muito dura; ideal para jin e shari. Muito valorizada na Indonésia e no Vietnã.'),
  ('Streblus asper', 'Serut (duối)', 'Moraceae', 'Sul e Sudeste Asiático', 'PERENE',
   'Sol pleno.', 'Regular.', 'Tropical.',
   'Folhas ásperas e tronco rústico; muito usado no Vietnã e na Indonésia.'),
  ('Ochna integerrima', 'Mai vàng (ocna)', 'Ochnaceae', 'Sudeste Asiático', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular; reduzir antes da floração.', 'Tropical.',
   'Símbolo do Tết no Vietnã: flores amarelas no fim do inverno.'),
  ('Barringtonia acutangula', 'Lộc vừng (barringtônia)', 'Lecythidaceae', 'Sul e Sudeste Asiático, Austrália', 'SEMI_CADUCA',
   'Sol pleno.', 'Abundante; tolera encharcamento.', 'Tropical.',
   'Muito popular no Vietnã. Cachos pendentes de flores vermelhas.'),
  ('Triphasia trifolia', 'Limãozinho (kingkit)', 'Rutaceae', 'Sudeste Asiático', 'PERENE',
   'Sol pleno.', 'Regular.', 'Tropical a subtropical.',
   'Folhas trifoliadas pequenas, espinhos e frutinhos vermelhos. Comum na Indonésia.'),

  -- ===================== NATIVAS DO CERRADO =====================
  ('Kielmeyera coriacea', 'Pau-santo', 'Calophyllaceae', 'Cerrado (Brasil)', 'SEMI_CADUCA',
   'Sol pleno.', 'Moderada; substrato muito drenado.', 'Tropical com estação seca.',
   'Casca grossa e corticosa, aparência envelhecida. Flores brancas.'),
  ('Hymenaea stigonocarpa', 'Jatobá-do-cerrado', 'Fabaceae', 'Cerrado (Brasil)', 'SEMI_CADUCA',
   'Sol pleno.', 'Moderada.', 'Tropical com estação seca.',
   'Folhas bifoliadas coriáceas; crescimento lento.'),
  ('Handroanthus ochraceus', 'Ipê-amarelo-do-cerrado', 'Bignoniaceae', 'Cerrado (Brasil)', 'CADUCIFOLIA',
   'Sol pleno.', 'Moderada; reduzir no inverno.', 'Tropical com estação seca.',
   'Tronco tortuoso e casca suberosa; floresce sem folhas no fim da seca.'),
  ('Tabebuia aurea', 'Craibeira (paratudo)', 'Bignoniaceae', 'Cerrado, Caatinga e Pantanal', 'CADUCIFOLIA',
   'Sol pleno.', 'Moderada.', 'Tropical com estação seca.',
   'Casca corticosa e flores amarelas; tolera seca.'),
  ('Eugenia dysenterica', 'Cagaiteira', 'Myrtaceae', 'Cerrado (Brasil)', 'CADUCIFOLIA',
   'Sol pleno.', 'Regular.', 'Tropical com estação seca.',
   'Casca que descama em placas e tronco tortuoso.'),
  ('Stryphnodendron adstringens', 'Barbatimão', 'Fabaceae', 'Cerrado (Brasil)', 'SEMI_CADUCA',
   'Sol pleno.', 'Moderada.', 'Tropical com estação seca.',
   'Casca grossa e rugosa; folhas compostas.'),
  ('Byrsonima crassifolia', 'Murici', 'Malpighiaceae', 'Cerrado e América tropical', 'PERENE',
   'Sol pleno.', 'Moderada.', 'Tropical.',
   'Tronco tortuoso e flores amarelas.'),
  ('Campomanesia adamantium', 'Gabiroba-do-cerrado', 'Myrtaceae', 'Cerrado (Brasil)', 'SEMI_CADUCA',
   'Sol pleno.', 'Regular.', 'Tropical a subtropical.',
   'Arbusto com xilopódio (base engrossada); frutos comestíveis.'),
  ('Anadenanthera colubrina', 'Angico', 'Fabaceae', 'Cerrado, Caatinga e Mata Atlântica', 'SEMI_CADUCA',
   'Sol pleno.', 'Moderada.', 'Tropical.',
   'Folíolos miúdos e casca com cristas; engrossa rápido.'),
  ('Myracrodruon urundeuva', 'Aroeira-do-sertão', 'Anacardiaceae', 'Cerrado e Caatinga', 'CADUCIFOLIA',
   'Sol pleno.', 'Moderada; resistente à seca.', 'Tropical com estação seca.',
   'Madeira muito dura; espécie protegida (adquirir de viveiros legalizados). Seiva pode causar alergia.')
) AS v(nc, nome, familia, origem, tipo, luz, rega, clima, obs)
ON CONFLICT ("nomeCientifico") DO NOTHING;

-- Conferir:
-- SELECT "tipoDePlanta", count(*) FROM "Especie" GROUP BY 1 ORDER BY 1;
